[package]
name = "quote_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0-rc.5"
bincode = "2.0.1"
chrono = "0.4.42"
thiserror = "2"
serde = { version = "1.0.228", features = ["derive"] }
